decentraland/editor-sdk7

- .github/workflows/test.yaml
- package-lock.json
- package.json
- src/modules/bin.spec.ts
- src/modules/node.spec.ts
- src/modules/path.spec.ts
- src/modules/pkg.spec.ts
- src/modules/watch.spec.ts
- src/modules/workspace.spec.ts
- src/utils.ts
Add most of the resolved path to test against inverted slashes
Windows is a target platform for the editor, supporting the development and adding tests for that platform is very useful.
> chore: support development of extension in windows

- src/commands/init.ts
- src/modules/bin.ts
This PR adds the `--skip-install` flag to avoid using the global npm (which might not exist)
> fix: avoid using global npm

- src/commands/init.ts
Use `@dcl/sdk-commands` instead of `@dcl/sdk`. This fixes the "module @dcl/sdk does not have a binary" error:
> fix: use @dcl/sdk-commands instead of @dcl/sdk

- src/utils.ts
- src/views/run-scene/webview.ts
Handle the messages from iframe with preview mode to enable the console.log and console.error from the scene. 
Explorer counterpart (preview mode): https://github.com/decentraland/unity-renderer/pull/4621
https://github.com/decentraland/sdk/issues/631
> feat: receive console.log and console.error from scenes

- src/__mocks__/vscode.ts
- src/extension.ts
- src/modules/notification.spec.ts
- src/modules/notification.ts
- src/modules/npm.spec.ts
Closes https://github.com/decentraland/sdk/issues/647
This PR adds a new `notifyUpdate` helper that can be used to communicate updates of a particular module, and uses it to notify updates of the `@dcl/sdk` package. We could reuse it later if we want to track other packages, or the extension itself.
> feat: notify updates in the SDK

- package-lock.json
- package.json
- src/views/run-scene/webview.ts
This PR upgrades `@dcl/sdk` to [v7.1.3](https://github.com/decentraland/js-sdk-toolchain/releases/tag/7.1.3) and adds support for piping `console.log`s in the scene into the extension's Output tab.
> feat: pipe logs to extension output

- src/views/publish-scene/server.ts
> fix: publish scene detects compilation error with keyword `error`

- src/views/run-scene/server.ts
Fixes https://github.com/decentraland/sdk/issues/677
The issue was that we were not awaiting for the `child.kill()` method to kill the `npm start` process, which internally uses the `treeKill` utility to kill all the child process spawned by the main process (in this case, it was the `sdk-commands` process spawned by the `npm start` process).
By not awaiting the promise, the `treeKill` method could not complete gathering the pids of the child processes, since that is an async procedure in some platforms (on linux it requires executing a `ps` and in mac a `pgrep`).
> fix: process leak

- package-lock.json
- package.json
- src/modules/sdk.ts
- src/views/inspector/server.ts
- src/views/inspector/webview.ts
Upgrade `@dcl/sdk` to `v7.1.13`, also fixed issue where `@next` version of the sdk installed in the workspace would be downgraded to `@latest`, and made the `@dcl/inspector` to be served from the workspace's `node_modules`
> feat: upgrade @dcl/sdk to v7.1.13

- package-lock.json
- package.json
- src/commands/install.ts
- src/modules/notification.ts
- src/modules/npm.spec.ts
- src/modules/npm.ts
- src/views/inspector/webview.ts
This PR adds support for smart items on the Editor. 
It also removes the prompt for decentraland libraries, since that is not used anymore in SDK7.
Finally it also removes an await on the notification that says that the SDK has been updated, so it doesn't block the start of the dev server until the user acknowledges it.
> feat: add support for smart items

- package-lock.json
- package.json
This PR upgrades the package `@dcl/sdk` to the version to `7.4.5`
> chore: Update @dcl/sdk version to 7.4.5

- package-lock.json
- package.json
Upgrade `@dcl/sdk` to `v7.4.13`
* chore: bump catalyst-client by @marianogoldman in https://github.com/decentraland/js-sdk-toolchain/pull/923
* feat: update renderer by @cazala in https://github.com/decentraland/js-sdk-toolchain/pull/924
**Full Changelog**: https://github.com/decentraland/js-sdk-toolchain/compare/7.4.12...7.4.13
* remove kernel & unity logs in preview by @gonpombo8 in https://github.com/decentraland/unity-renderer/pull/6141
* fix: removed offset for SDK7 avatar position by @aixaCode in https://github.com/decentraland/unity-renderer/pull/6123
> feat: upgrade @dcl/sdk to v7.4.13

- src/modules/log.spec.ts
- src/modules/log.ts
Fixes https://github.com/decentraland/sdk/issues/860
The problem was that some logs from `@dcl/sdk-commands` are meant for the console and they contain ansii escape codes to format the output. These don't work on VSCode's output tab, so I fltered them out using a regex that I took from [StackOverflow](https://stackoverflow.com/questions/7149601/how-to-remove-replace-ansi-color-codes-from-a-string-in-javascript).
Added a test too.
> fix: remove ansii escape codes from vscode logs

- .github/workflows/package.yaml
- .gitignore
- .vscodeignore
- src/extension.ts
- src/modules/npm.spec.ts
- src/modules/npm.ts
The CI is currently failing to publish new versions of the extension because the size of the package is too large (+400mb). See [v1.48.0](https://github.com/decentraland/editor-sdk7/actions/runs/8523729302) and [v1.48.1](https://github.com/decentraland/editor-sdk7/actions/runs/8559260738).
This PR ignores everything in `node_modules` except for `npm` and it uses it to install the rest of the dependencies when the extension is activated. This reduces the size of the package to just 4mb:
It will store the extension version in global storage so it doesn't install the dependencies again for a version that has already been installed.
A few test were added to keep the coverage at 100%.
It also adds the latest version and commit hash to the artifact created on each PR, this makes it easier to …
> fix: publish

- package-lock.json
- package.json
Upgrade `@dcl/sdk` to [v7.4.18](https://github.com/decentraland/js-sdk-toolchain/releases/tag/7.4.18)
* fix: prevent race condition between loading Nodes component and GLTFs by @cazala in https://github.com/decentraland/js-sdk-toolchain/pull/933
**Full Changelog**: https://github.com/decentraland/js-sdk-toolchain/compare/7.4.17...7.4.18
> feat: upgrade @dcl/sdk to v7.4.18

- package-lock.json
- package.json
This PR upgrades the package `@dcl/sdk` to the version `7.4.21`
> chore: Upgrade the @dcl/sdk package to the version 7.4.21

- .github/workflows/package.yaml
- src/extension.ts
- src/modules/npm.spec.ts
- src/modules/npm.ts
- src/modules/spawn.ts
It has been reported that the `npm install` sometimes fails and it can't recover until manually cleaning the cache. This PR wraps the installation of the extension in a try/catch, and if it fails, it cleans the cache (`npm cache clean --force`) and tries again.
> feat: clean cache and retry on error

- src/__mocks__/vscode.ts
- src/extension.ts
- src/modules/fs.spec.ts
- src/modules/fs.ts
- src/modules/npm.spec.ts
- src/modules/npm.ts
- src/modules/path.spec.ts
- src/modules/path.ts
This PR adds two steps to the installation of the extension dependencies:
1. First, it restores the `node_modules` from the global cache (if it exists) by copying the `node_modules` from `{globalStorage}/.cache/node_modules` into `{extensionPath}/node_modules`
2. Second, it installs the extension's dependencies by running `npm install`
3. Third, it copies the freshly installed `node_modules` into the global cache at `{globalStorage}/.cache/node_modules` to keep the cache updated.
This makes the installation process faster for future version because it doesn't run the `npm install` on an empty `node_modules` but instead it keeps the ones from the previous version.
> feat: cache node modules

- src/extension.ts
Only add `main.crdt` if the workspace is a DCL project
> fix: only add main.crdt if the workspace is a DCL project

- src/modules/npm.spec.ts
- src/modules/npm.ts
- src/modules/sdk.spec.ts
- src/modules/sdk.ts
Prompt the user if they want to update the SDK instead of doing it automatically.
Allows the user to ignore this version to prevent showing the prompt on future activations of the extension.
> feat: prompt user instead of forcing the update of sdk
