decentraland/editor-sdk7

- package-lock.json
- package.json
Upgrade to latest release of `@dcl/sdk`
> chore: upgrade @dcl/sdk to v7.0.6

- package-lock.json
- package.json
Upgrade `@dcl/sdk` to version `7.1.0`
> chore: upgrade to @dcl/sdk@7.1.0

- package-lock.json
- package.json
Upgrade `@dcl/sdk` to [v7.1.2](https://github.com/decentraland/js-sdk-toolchain/releases/tag/7.1.2)
> feat: upgrade sdk to v7.1.2

- package-lock.json
- package.json
- src/commands/inspector.ts
- src/views/inspector/server.ts
- src/views/inspector/webview.ts
Serve `@dcl/inspector` from `node_modules`
> feat: serve inspector

- src/modules/spawn.spec.ts
- src/modules/spawn.ts
- src/views/publish-scene/server.ts
- src/views/run-scene/server.ts
> use sdk-commands for deploy

- package-lock.json
- package.json
- src/modules/spawn.spec.ts
Upgrade `@dcl/sdk` to version `v7.1.4`
> feat: sdk 7.1.4

- package-lock.json
- package.json
Upgrade `@dcl/sdk` to `v7.1.5`
> feat: upgrade @dcl/sdk to v7.1.5

- src/commands/init.ts
- Dependency https://github.com/decentraland/js-sdk-toolchain/pull/560
Choose the type of project when initializing a new project.
> feat: add ask for project type

- src/commands/init.ts
Make standard template go first
> fix: flip options

- package-lock.json
- package.json
- src/views/run-scene/server.ts
Remove failing detection by the `error` pattern
Bump `@dcl/sdk` and inspector with fixes
> fix: remove reject pattern in RunScene server

- package-lock.json
- package.json
Upgrade `@dcl/sdk` to `v7.1.16`
> feat: upgrade @dcl/sdk to v7.1.16

- package-lock.json
- package.json
Upgrade `@dcl/sdk` to `v7.1.17`
> feat: upgrade @dcl/sdk to v7.1.17

- package.json
closes https://github.com/decentraland/sdk/issues/824
> fix: move inspector buttom to viewsWelcome

- src/commands/install.ts
- src/commands/uninstall.ts
- src/views/run-scene/webview.ts
closes https://github.com/decentraland/sdk/issues/858
closes https://github.com/decentraland/sdk/issues/861
> fix: install package placeholder + preview errors output

- .github/workflows/package.yaml
closes https://github.com/decentraland/sdk/issues/882
> feat: add upload artifact workflow

- package-lock.json
- package.json
Upgrade `@dcl/sdk` to version [7.3.0](https://github.com/decentraland/js-sdk-toolchain/releases/tag/7.3.0)
> feat: upgrade @dcl/sdk to v7.3.0

- package-lock.json
- package.json
Upgrade `@dcl/sdk` to version `7.3.7`
> feat: upgrade sdk to v7.3.7

- package-lock.json
- package.json
- src/views/inspector/webview.ts
Upgrade `@dcl/sdk` to version `v7.3.14`
> feat: upgrade sdk to v7.3.14

- package-lock.json
- package.json
Upgrade `@dcl/sdk` to `v7.3.15`
> feat: upgrade sdk to v7.3.15

- package-lock.json
- package.json
Upgrade `@dcl/sdk` to `v7.3.18`
> feat: upgrade sdk v7.3.18

- package-lock.json
- package.json
This PR upgrades the package `@dcl/sdk`
> chore: Upgrade @dcl/sdk package

- src/views/publish-scene/utils.ts
Fixes scene.json world name validation to allow ens names
> fix: world name from scene.json validation

- package-lock.json
- package.json
- src/modules/analytics.spec.ts
- src/modules/analytics.ts
- src/views/inspector/webview.ts
This PR sends the project id to the inspector to track scenes and items.
> feat: Add new project id property to identify projects on analytics

- src/views/publish-scene/server.ts
Fixes https://github.com/decentraland/sdk/issues/1034
> fix: wait for process to exit

- package-lock.json
- package.json
Upgrade `@dcl/sdk` to `v7.3.31`
> feat: upgrade @dcl/sdk

- package-lock.json
- package.json
> feat: upgrade sdk to v7.3.41

- package-lock.json
- package.json
This PR upgrades the package @dcl/sdk version
> chore: Upgrade @dcl/sdk package version

- package-lock.json
- package.json
This PR upgrades the package `@dcl/sdk` to version 7.4.3
> chore: Upgrade package @dcl/sdk to version 7.4.3

- package.json
closes https://github.com/decentraland/sdk/issues/1054
closes https://github.com/decentraland/sdk/issues/1055
closes https://github.com/decentraland/sdk/issues/1056
> some renaming + browser open for commands

- package-lock.json
- package.json
feat: upgrade `@dcl/sdk` to `v7.4.9`
> feat: upgrade @dcl/sdk to v7.4.9

- package-lock.json
- package.json
Upgrade `@dcl/sdk` to `v7.4.12`
> feat: upgrade @dcl/sdk to v7.4.12

- package-lock.json
- package.json
Upgrade `@dcl/sdk` to `v7.4.14`
* fix: nested entities by @cazala in https://github.com/decentraland/js-sdk-toolchain/pull/925
**Full Changelog**: https://github.com/decentraland/js-sdk-toolchain/compare/7.4.13...7.4.14
> feat: upgrade @dcl/sdk to v7.4.14

- src/modules/npm.spec.ts
- src/modules/npm.ts
Show a notification when updating editor
> feat: show a notification with progressbar when updating editor

- package-lock.json
- package.json
Upgrade `@dcl/sdk` to `v7.4.17`
> feat: upgrade @dcl/sdk to v7.4.17

- package-lock.json
- package.json
Upgrade `@dcl/sdk` to `v7.5.0`
* remove old observabels logic by @gonpombo8 in https://github.com/decentraland/js-sdk-toolchain/pull/935
* feat: easy floor placing by @cazala in https://github.com/decentraland/js-sdk-toolchain/pull/941
* feat: Game smart items simplified view by @cyaiox in https://github.com/decentraland/js-sdk-toolchain/pull/943
* feat: add more avatar attach points by @AlejandroAlvarezMelucciDCL in https://github.com/decentraland/js-sdk-toolchain/pull/947
* feat: hide metrics by @cazala in https://github.com/decentraland/js-sdk-toolchain/pull/952
* DevExp improvements by @gonpombo8 in https://github.com/decentraland/js-sdk-toolchain/pull/950
* Add new Scene Layout by @nicoecheza in https://github.com/decentraland/js-sdk-toolchain/pull/945
* feat: upgrade @dcl/explorer …
> feat: upgrade @dcl/sdk to v7.5.0

- package-lock.json
- package.json
This PR upgrades the package `@dcl/sdk` to the version 7.5.1.
> feat: Upgrade @dcl/sdk package

- .github/workflows/test.yaml
- src/commands/browser.ts
- src/commands/inspector.ts
- src/commands/restart.ts
- src/commands/start.ts
- src/extension.ts
- src/utils.ts
- src/views/run-scene/server.ts
- src/views/run-scene/webview.ts
Reverts decentraland/editor-sdk7#124
> Revert "disable preview"
